name: Build mock packages

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: self-hosted

    strategy:
      fail-fast: false

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0

      - name: Build docker images
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          file: cuda-mock-packages/Dockerfile
          push: false
          tags: cuda_mock_builder:0.0.1
          platforms: linux/amd64
          load: true
          cache-from: type=local,src=.buildx-cache
          cache-to: type=local,dest=.buildx-cache,mode=max

      - name: Create cuda_mock_build_output directory
        run: mkdir -p cuda_mock_build_output

      - name: Run Docker container and copy files
        run: |
          container_id=$(docker create cuda_mock_builder:0.0.1)
          docker start $container_id
          docker cp $container_id:/mocks/ ./cuda_mock_build_output/
          docker rm $container_id

      - name: Create GitHub Release and Upload DEB packages
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cuda_mocks
          name: Cuda mock packages
          body: "Mock packages for nvidia-open and cuda-drivers"
          draft: false
          prerelease: false
          files: |
            cuda_mock_build_output/mocks/*.deb

      - name: Cleanup
        run: rm -rf cuda_mock_build_output
