name: Build nccl tests binaries

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        build:
          - cuda_version: 12.4.1
            build_args:
              BASE_IMAGE=cr.eu-north1.nebius.cloud/soperator/nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build docker images
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          file: nccl-tests/Dockerfile
          push: false
          tags: nccl_tests_builder:${{ matrix.build.cuda_version }}
          platforms: linux/amd64
          load: true
          build-args: |
            ${{ matrix.build.build_args }}
          cache-from: type=local,src=.buildx-cache
          cache-to: type=local,dest=.buildx-cache,mode=max

      - name: Create nccl_tests_build_output directory
        run: mkdir -p nccl_tests_build_output

      - name: Run Docker container and copy files
        run: |
          container_id=$(docker create nccl_tests_builder:${{ matrix.build.cuda_version }})
          docker start $container_id
          docker cp $container_id:/usr/src/nccl-tests/build/nccl-tests-perf.tar.gz ./nccl_tests_build_output/
          docker stop $container_id
          docker rm $container_id

      - name: Create GitHub Release and Upload NCCL tests
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nccl_tests_${{ matrix.build.cuda_version }}
          name: NCCL tests for cuda ${{ matrix.build.cuda_version }}
          draft: false
          prerelease: false
          files: |
            nccl_tests_build_output/nccl-tests-perf.tar.gz

      - name: Cleanup
        run: rm -rf nccl_tests_build_output/*.tar.gz
