name: Build pyxis

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        slurm:
          - version: 24.05.6
        enroot:
          - version: 3.5.0
        pyxis:
          - version: 0.21.0
        image:
          - file: pyxis/Dockerfile
            push: false
            platforms: linux/amd64
            load: true
            build_args:
              BASE_IMAGE=cr.eu-north1.nebius.cloud/soperator/ubuntu:jammy

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build docker images
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          file: ${{ matrix.image.file }}
          push: ${{ matrix.image.push }}
          tags: pyxis_builder:slurm_${{ matrix.slurm.version }}_enroot_${{ matrix.enroot.version }}_pyxis_${{ matrix.pyxis.vesion }}
          platforms: ${{ matrix.image.platforms }}
          load: ${{ matrix.image.load }}
          build-args: |
            ${{ matrix.image.build_args }}
            SLURM_VERSION=${{ matrix.slurm.version }}
            ENROOT_VERSION=${{ matrix.enroot.version }}
            PYXIS_VERSION=${{ matrix.pyxis.version }}
          cache-from: type=local,src=.buildx-cache
          cache-to: type=local,dest=.buildx-cache,mode=max

      - name: Create pyxis_build_output directory
        run: mkdir -p pyxis_build_output

      - name: Run Docker container and copy files
        run: |
          container_id=$(docker create pyxis_builder:slurm_${{ matrix.slurm.version }}_enroot_${{ matrix.enroot.version }}_pyxis_${{ matrix.pyxis.vesion }})
          docker start $container_id
          docker cp $container_id:/usr/src/debs/ ./pyxis_build_output/
          docker stop $container_id
          docker rm $container_id

      - name: Create GitHub Release and Upload DEB packages
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: pyxis-${{ matrix.pyxis.version }}_slurm_${{ matrix.slurm.version }}_enroot_${{ matrix.enroot.version }}
          name: Pyxis ${{ matrix.pyxis.version }}
          body: Pyxis ${{ matrix.pyxis.version }} for Slurm ${{ matrix.slurm.version }} and Enroot ${{ matrix.enroot.version }}
          draft: false
          prerelease: false
          files: |
            pyxis_build_output/debs/*.deb
            

      - name: Cleanup
        run: rm -rf pyxis_build_output/*.deb
