name: Build slurm packages

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        slurm:
          - version: 24.05.6
        image:
          - file: slurm-packages/Dockerfile
            push: false
            platforms: linux/amd64
            load: true
            build_args:
              BASE_IMAGE=cr.eu-north1.nebius.cloud/soperator/nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Get short commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Build docker images
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          file: ${{ matrix.image.file }}
          push: ${{ matrix.image.push }}
          tags: slurm_packages:${{ matrix.slurm.version }}-${{ env.SHORT_SHA }}
          platforms: ${{ matrix.image.platforms }}
          load: ${{ matrix.image.load }}
          build-args: |
            ${{ matrix.image.build_args }}
            SLURM_VERSION=${{ matrix.slurm.version }}
          cache-from: type=local,src=.buildx-cache
          cache-to: type=local,dest=.buildx-cache,mode=max

      - name: Create slurm_packages_output directory
        run: mkdir -p slurm_packages_output

      - name: Run Docker container and copy files
        run: |
          container_id=$(docker create slurm_packages:${{ matrix.slurm.version }}-${{ env.SHORT_SHA }})
          docker start $container_id
          docker cp $container_id:/usr/src/debs/ ./slurm_packages_output/
          docker stop $container_id
          docker rm $container_id

      - name: Create GitHub Release and Upload DEB packages
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: slurm-packages-${{ matrix.slurm.version }}
          name: Slurm packages ${{ matrix.slurm.version }}
          draft: false
          prerelease: false
          files: |
            slurm_packages_output/debs/*.deb
            

      - name: Cleanup
        run: rm -rf slurm_packages_output/*.deb
