name: Build slurm packages on ${{ matrix.platform }} platform

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        slurm:
          - version: 24.05.7
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            runner: X64
            ld_library_path: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/targets/x86_64-linux/lib:/usr/mpi/gcc/openmpi-${OPENMPI_VERSION}/lib
          - platform: linux/arm64
            runner: ARM64
            ld_library_path: /lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/usr/local/nvidia/lib:/usr/local/cuda-12.4/targets/sbsa-linux/lib/:/usr/mpi/gcc/openmpi-${OPENMPI_VERSION}/lib

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Get short commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Build docker images
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          file: slurm-packages/Dockerfile
          push: false
          tags: slurm_packages:${{ matrix.slurm.version }}-${{ env.SHORT_SHA }}
          platforms: ${{ matrix.platform }}
          load: true
          build-args: |
            BASE_IMAGE=cr.eu-north1.nebius.cloud/soperator/nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
            SLURM_VERSION=${{ matrix.slurm.version }}
            LD_LIBRARY_PATH=${{ matrix.ld_library_path }}
          cache-from: type=local,src=.buildx-cache
          cache-to: type=local,dest=.buildx-cache,mode=max

      - name: Create slurm_packages_output directory
        run: mkdir -p slurm_packages_output

      - name: Run Docker container and copy files
        run: |
          container_id=$(docker create slurm_packages:${{ matrix.slurm.version }}-${{ env.SHORT_SHA }})
          docker start $container_id
          docker cp $container_id:/usr/src/debs/ ./slurm_packages_output/
          docker stop $container_id
          docker rm $container_id

      - name: Create GitHub Release and Upload DEB packages
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: slurm-packages-${{ matrix.slurm.version }}
          name: Slurm packages ${{ matrix.slurm.version }}
          draft: false
          prerelease: false
          files: |
            slurm_packages_output/debs/*.deb
            

      - name: Cleanup
        run: rm -rf slurm_packages_output/*.deb
